### ISSUE TITLE
Android Player audio doesn't call on ended event

### ISSUE THREAD

**Issue by uttu90** [futurice/react-native-audio-toolkit#101]
the Player.on('ended') function doesn't fire when the audio reaches to the end.
Only occurs on android Player.

**Comment by moonstruck** [comment]
Have you checked with console.log ?
I've found on ended event working on every versions of android.
You may post your code blocks.

**Comment by uttu90** [comment]
Hi,
I see it OK now. It's because the Player.on('ended') function in android return variable both error and non-error.
