### ISSUE TITLE
recorder did not record sound  after i play audio using avfoundation(native code) during recording 

### ISSUE THREAD

**Issue by awaisAndr** [futurice/react-native-audio-toolkit#118]
let say i start recording and when i reach at 10 sec recording now i played a sound using native code (avfoundation) but recording was also running during this action ,from this playing action recording keep showing the recording in progress but actually it do not catch any sound from microphone

**Comment by amitkaz** [comment]
I had the same problem and fixed it by changing line 80 of AudioRecorder.m
from:
`[audioSession setCategory:AVAudioSessionCategoryRecord error:&error];`
to:
    `[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionMixWithOthers | AVAudioSessionCategoryOptionDefaultToSpeaker error:&error];`

**Comment by awaisAndr** [comment]
thanks i will try

**Comment by xstable** [comment]
> I had the same problem and fixed it by changing line 80 of AudioRecorder.m
> from:
> `[audioSession setCategory:AVAudioSessionCategoryRecord error:&error];`
> to:
> `[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionMixWithOthers | AVAudioSessionCategoryOptionDefaultToSpeaker error:&error];`

This would be a nice Feature for the component ( maybe as optional setting for recording): 

_typeOfRecording: playAndRecord | onlyRecord_

**Comment by awaisAndr** [comment]
thanks @FruitieX  @amitkaz it is working
