### ISSUE TITLE
Get access to the recorded file?

### ISSUE THREAD

**Issue by ohtangza** [futurice/react-native-audio-toolkit#14]
Is there anyway I can get the absolute path for the recorded file in order to open and upload it to remote server?

**Comment by egunsoma** [comment]
How did you do it? :)

**Comment by mojtaba-hajishah** [comment]
@ohtangza could you share the answer?

**Comment by egunsoma** [comment]
I managed to solve this @mojtaba-hajishah, here is my solution:

```
    this.rec = new RNRecorder("filename.mp4");
    this.rec.prepare((err, fsPath) => {
      console.log('fsPath', fsPath);
      this.setState({ fsPath })
      if (err) {
        console.log('error at reloadRecorder():');
        console.log(err);
      }
    });
    this.rec.record();
```

Where **fsPath** is what you need.

**Comment by mojtaba-hajishah** [comment]
Thanks @egunsoma 
I get something like this: /data/user/0/com.modone/files/test.mp4
but where the heck is that? I can't find the actual file.
I intend to send it to an API.

**Comment by egunsoma** [comment]
You probably need [React Native File System](https://github.com/itinance/react-native-fs) for that.

**Comment by augustopablo** [comment]
Is that file destroyed itself? Or do I have to remove them everytime I record?
