### ISSUE TITLE
Track still plays in bg despite 'continuesToPlayInBackground' being false

### ISSUE THREAD

**Issue by Naoto-Ida** [futurice/react-native-audio-toolkit#17]
The issue is addressed as is in the title. It happens on iOS, haven't tested on Android yet.

Here's my code:

```
this.player = new Player(data.preview_url, {continuesToPlayInBackground: false})
```

I back out of the app and it's still playing.
Note that I do not have the background audio permission on.

**Comment by ohtangza** [comment]
When I tested on iOS with 1.0.5, it stopped playing when the app went background by pressing Home button. Tested on iOS 10 device.

**Comment by Naoto-Ida** [comment]
Yeah, now it started stopping... wonder why. Closing this.
