### ISSUE TITLE
Playing back local files for iOS

### ISSUE THREAD

**Issue by ohtangza** [futurice/react-native-audio-toolkit#18]
Any way to play locally downloaded file (other than assets included in iOS project)?

**Comment by ohtangza** [comment]
I found solution by myself. We need "file://" prefix in front to the absolute file path. I'll add this on documentation.

**Comment by dwilt** [comment]
@ohtangza thanks for fixing/finding this. I didn't think this plugin supported it but luckily I saw your closed issue. Hope you didnt' forget to update the docs!

**Comment by ohtangza** [comment]
@dwilt Thanks for your reminder. I submitted a pull request for adding this instruction: https://github.com/futurice/react-native-audio-toolkit/pull/26/commits/03052b08d8fca2d7915c987d49a84f65f6e8d328 
It will be soon available online. Have a nice day!

**Comment by abhi-nahi** [comment]
No, It's still not updated. Documents still says that the feature is compatible for Android only. I'm glad I found this.

**Comment by Aung-Myint-Thein** [comment]
Is there an example to play a local audio file, please?

**Comment by DevMMI** [comment]
> Is there an example to play a local audio file, please? I included the file in the js source codes but not sure how to read the file.
Use ReactNativeFS to get the file path, then use that url to initialize Player(path)
```
RNFS.readDir(RNFS.DocumentDirectoryPath)
    .then((result) => {
let path = "file://"+result[0].path
```

**Comment by Toni-Stark** [comment]
@DevMMI This is Android
