### ISSUE TITLE
[ANDROID] App crashes while calling new Player().play()

### ISSUE THREAD

**Issue by cherniv** [futurice/react-native-audio-toolkit#31]
Hey, on Android, when i'm running new Player(...).play() the app crashes, this is what i see in logs:

<img width="655" alt="android_audio_toolkit_bug" src="https://cloud.githubusercontent.com/assets/3829914/24607458/8cd77ba4-187a-11e7-9644-8826cb47a45e.png">

**Comment by ohtangza** [comment]
Lots of people use this library without problem in Android. Do you elaborate more on your error?

For example, if `new Player()` contains a valid object, or if `Player.repare()` work.

**Comment by cherniv** [comment]
Lets leave it, i'm not sure what it was, using another library now
