### ISSUE TITLE
add progress

### ISSUE THREAD

**Issue by hkhungit** [futurice/react-native-audio-toolkit#4]
Hi guy.
I added a function progress in android and ios from your code. I hope you grant me a permission request to your project. You can see it at https://github.com/hkhungit/react-native-audio-toolkit

Thanks!

**Comment by FruitieX** [comment]
Pull request (finally) merged. Very sorry for the embarrassing delay on my part. :(

**Comment by ovy9086** [comment]
so was this merged ? I can't find any way to get the progress on the player

**Comment by luisfuertes** [comment]
Any update about player.on('progress") feature?

**Comment by Aung-Myint-Thein** [comment]
in src/Player.js, 'case progress' is still `//TODO` so far
