### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by pudility** [futurice/react-native-audio-toolkit#50]
When I try to build for android, I get this error:

```
:react-native-audio-toolkit:incrementalReleaseJavaCompilationSafeguard
:react-native-audio-toolkit:compileReleaseJavaWithJavac
:react-native-audio-toolkit:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/zoe/Developer/podcast/node_modules/react-native-audio-toolkit/android/lib/src/main/java/com/futurice/rctaudiotoolkit/AudioPackage.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-audio-toolkit:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio-toolkit:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
However if I run on IOS it works just fine. 

I have followed the instructions for installing on android.

**Comment by tomershohet** [comment]
+1

**Comment by henrych4** [comment]
Same thing happened to me. Comment the @override line may help to solve the problem/

**Comment by pudility** [comment]
@henrych4 that (very surprisingly) worked, however I had to remove @override from many of my modules. Do you know why that is? Thanks for the help!

**Comment by pudility** [comment]
I am not sure if this is related, but I am now getting this in the console:

`Running application "podcast" with appParams: {"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF` 

any ideas?

**Comment by henrych4** [comment]
It seems that ReactPackage Interface does not contain those methods for override.

Reference: [https://github.com/ivpusic/react-native-image-crop-picker/issues/404](url)
