### ISSUE TITLE
undefined is not an object (evaluating 'RCTAudioPlayer.prepare')

### ISSUE THREAD

**Issue by jose920405** [futurice/react-native-audio-toolkit#55]
Error is showing when call

```
this.player = new Player(url, {
      autoDestroy: false
    }).prepare((err) => {
      if (err) {
        console.log('error at play():');
        console.log(err);
      } else {
        console.log('Here prepare success!!!');
      }
    });
```

**Comment by Beclamide** [comment]
Did you solve this error? Would be good to document the fix 🙂

**Comment by jose920405** [comment]
Yeah. I close this issue, because the problem was mine and not the library

My final code:

```
let url = SERVER_URL + this.props.url;

this.player = new Player(url, { autoDestroy: false }).prepare((err) => {
  if (err) {
    console.log('error at play():');
    console.log(err);
  } else {
    console.log('Here prepare success!!!');
    this.player.playPause((err, playing) => {
      if (err) {
        console.log('failed to load the sound', error);
        return;
      }
      console.log('Here PLAY!!! success!!!');
    });
  }
});
```

**Comment by webmasterersm** [comment]
Saludos hermano, tengo ese mismo problema, como lo resolviste?

**Comment by jose920405** [comment]
hola @webmasterersm 

Ha pasado mucho tiempo desde que corregí esto. Para ser sincero, no recuerdo exactamente cual era el problema. Solo recuerdo que era un error `capa 8` 😂  y no tenía nada que ver con este módulo en si. En el comentario anterior te dejé el código final que tengo funcionando en estos momentos en mi aplicación.

**Comment by webmasterersm** [comment]
Ok @jose920405 

Muchas gracias.
