### ISSUE TITLE
Project activity, future updates / releases

### ISSUE THREAD

**Issue by hmaster0** [futurice/react-native-audio-toolkit#56]
Hello @fruitieX is this project still alive, any info whether you plan to still support / maintain this library? I see that the master has new commits which haven't been released to npm and there's a PR that fixes build fails on RN 0.47.1 and above which too hasn't been merged to the master. Please let me know what are your plans for this project as I very much like the mediaplayer API implementation as it is implemented here.

**Comment by prakashsejwani** [comment]
+1

**Comment by FruitieX** [comment]
Personally I don't have time to maintain it, if someone wants to volunteer as maintainer it would be great! I can certainly push a new release on npm though, seeing that the PR seems to fix compatibility with newer RN versions. It has now been merged to master.

**Comment by hmaster0** [comment]
Thanks @FruitieX , a new release on npm would be good for now.

**Comment by hmaster0** [comment]
Hey @FruitieX , I don't want to sound pushy but could you please look into releasing the new master on npm. It'd be very helpful. Thank you.

**Comment by FruitieX** [comment]
@hmaster0 Sorry for the wait, I'll try to push a new release today. In the meantime, using `npm install futurice/react-native-audio-toolkit` should work for installing the latest development version in master branch.

**Comment by FruitieX** [comment]
v1.0.6 is out based on https://github.com/futurice/react-native-audio-toolkit/tree/1.0.6

**Comment by hmaster0** [comment]
Awesome, @FruitieX . Thanks a lot.

**Comment by tmaly1980** [comment]
@FruitieX can you at least update your README to inform people that this isn't being maintained anymore, and maybe point people toward someone else's cloned repo who is more willing to maintain? That way we aren't thinking this works when there are clear bugs that sit unresolved for months (especially despite patches being out there).
