### ISSUE TITLE
is it possible to support to play in the background on iOS ?

### ISSUE THREAD

**Issue by inspireui** [futurice/react-native-audio-toolkit#61]
please update version to support continuesToPlayInBackground  on iOS ?

**Comment by kesha-antonov** [comment]
Just include in your Info.plist ```audio``` in ```BackgroundModes```

**Comment by inspireui** [comment]
resolved

**Comment by JustinKasad** [comment]
Just add

`<key>UIBackgroundModes</key>
    <array>
      <string>audio</string>
    </array>`

to you info.plist file
