### ISSUE TITLE
Not able to Play from network in Android.throwing error

### ISSUE THREAD

**Issue by arunkrishna39** [futurice/react-native-audio-toolkit#70]
3613-8999/com.audiotest E/AudioPlayerModule: playerId 0 not found.
11-30 15:54:31.764 3613-8999/com.audiotest D/AudioPlayerModule: dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                java.lang.Thread.getStackTrace(Thread.java:580)
                                                                com.futurice.rctaudiotoolkit.AudioPlayerModule.errObj(AudioPlayerModule.java:105)
                                                                com.futurice.rctaudiotoolkit.AudioPlayerModule.errObj(AudioPlayerModule.java:125)
                                                                com.futurice.rctaudiotoolkit.AudioPlayerModule.play(AudioPlayerModule.java:353)
                                                                java.lang.reflect.Method.invoke(Native Method)
                                                                java.lang.reflect.Method.invoke(Method.java:372)
                                                                com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                                com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
                                                                com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                android.os.Handler.handleCallback(Handler.java:739)
                                                                android.os.Handler.dispatchMessage(Handler.java:95)
                                                                com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                android.os.Looper.loop(Looper.java:135)
                                                                com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                java.lang.Thread.run(Thread.java:818) #

**Comment by lefrankleal** [comment]
am getting this error too, some help please?

**Comment by muhammadarsal** [comment]
Was anyone able to fix this?
