### ISSUE TITLE
how to achieve rewind/re-play?

### ISSUE THREAD

**Issue by jalal246** [futurice/react-native-audio-toolkit#88]
Hi there, 
despite looping which i don't want it on ,my case, i tried. I am trying to play a track after it ended by revoking    play() but it wont work!. it plays the track once, then 

```
const someMusic = new Player('whatEver.mp3');

// this  function will be called multiple times
playSound(){
someMusic.play() // just play one time regardless of however i called it
}
```

i tried playPause() but i got the same problem.

**Comment by KalebMatthews** [comment]
I believe what is happening is the position is not being reset so when you try to play it again the current position is still at the end of the file. You can try a simple someMusic.seek(0) then play to test.

**Comment by jalal246** [comment]
@KalebMatthews  same problem it works one time only

**Comment by KalebMatthews** [comment]
@jalal246 So judging by your original comment I am assuming you want it to stop when it plays once then stop and only play again when the play button is pressed? If that is the case and the seek action after it finishes didn't work you can turn on the looping then add the looped event to stop the playing when it looped. That will reset the pointer properly and create the "no looping" behavior I think you want.

`
const someMusic = new Player('whatEver.mp3');

someMusic.looping = true;
someMusic.on("looped", () => someMusic.pause());

playSound(){
    someMusic.play();
}`

The alternative is to use the ended event and seek back to 0 if that is not what you tried before. Just listing everything I can think of. Hope this works and it help!

**Comment by jalal246** [comment]
@KalebMatthews This is absolutely helpful, Thanks!
